### ISSUE TITLE
APIs | Populate "price" column

### ISSUE THREAD

**Issue by samnet** [samnet/InsideX#3]
Goal: "Price" column is currently populated with stubs only
Implementation: get the price from your favorite API and populate the "price" cells. 
Design choice: how often should price be refreshed? Upon opening the extension popup, every 30 minutes? I am open to anything here.

**Comment by pasupulaphani** [comment]
Upon opening the view, we can make a call to get the prices. but I couldn't find the prices API and many are rate-limiting (1 req / 2 seconds). Any suggestions?

**Comment by pasupulaphani** [comment]
Used: https://p.nomics.com/cryptocurrency-bitcoin-api/ Free api for now.
