### ISSUE TITLE
Make sure same token cannot appear twice in table

### ISSUE THREAD

**Issue by samnet** [samnet/InsideX#6]
Don't want the user to be able to add the same token twice to the table.
If user selects token A, there should thus be two options:
- token A doesn't appear in list of suggestions
- token A appears in list of suggestions but nothing happens when you select it. 

We could have: start with an array of all tokens, modify this array as you add/delete rows from the table.

**Comment by pasupulaphani** [comment]
@samnet made a couple of updates that would fix the issue. please see my edits

**Comment by samnet** [comment]
Top, thanks.
